dist: bionic
language: python
python:
  - "3.7"
before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
  - docker version && docker buildx version
install:
  - pip install poetry
  - nvm install 7.4
  - npm install -g eslint
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
script:
  - make test docker-multi
after_success:
  - coveralls
